function[G_SS] = G_SS_fun(p,n)
    %p is the input parameters, and s is the section of the blade.
    Theta_minus = Theta_minus_fun(p,n);
    k_bar = k_bar_fun(p,n);
    kappa_bar = kappa_bar_fun(p,n);
    
    G_SS = @(freq) (1+epsilon).*exp(1i.*(2.*kappa_bar+Theta_minus)).*sin(Theta_minus-2.*kappa_bar)./...
    (Theta_minus-2.*kappa_bar)+(1-epsilon).*exp(1i.*(-2.*kappa_bar+Theta_minus)).*...
    sin(Theta_minus+2.*kappa_bar)./(Theta_minus+2.*kappa_bar)+(1+epsilon).*(1-1i)./...
    (2.*(Theta_minus-2.*kappa_bar)).*exp(4.*1i.*k_bar).*fresnel(4.*kappa_bar)-(1-epsilon)...
    .*(1+1i)./(2.*(Theta_minus+2.*kappa_bar)).*exp(4.*1i.*k_bar).*fresnel(4.*kappa_bar)...
    +exp(2.*1i.*Theta_minus)./2.*sqrt(2.*kappa_bar./Theta_minus).*fresnel(2.*Theta_minus).*...
    ((1-epsilon).*(1+1i)./(Theta_minus+2.*kappa_bar)-(1+epsilon).*(1+1i)./(Theta_minus-2.*kappa_bar));%k_x might be a vector; %Maybe change M
end